### ISSUE TITLE
Missing Schema

### ISSUE THREAD

**Issue by jason-a-alexander** [nekromant/ezshare#1]
When running the following command, I get the following error message.   I wonder if python 3.11 is forcing strict URL building?  This is running on Mac OS.  

ezshare-cli -r -w -d / -t /Users/jalexand/Desktop/SD_Card/

Synchronizing remote / -> /Users/jalexand/Desktop/SD_Card/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/ezshare-cli", line 8, in <module>
    sys.exit(__main__.main())
             ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ezshare/__main__.py", line 161, in main
    _handle_args_once(args, s)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ezshare/__main__.py", line 144, in _handle_args_once
    s.sync(args.download, args.target, recursive=args.recursive)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ezshare/__main__.py", line 125, in sync
    self._sync_list(todo, local_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ezshare/__main__.py", line 115, in _sync_list
    self._dload(v, path.join(local_dir, k))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ezshare/__main__.py", line 77, in _dload
    response = requests.head(link)
               ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/api.py", line 100, in head
    return request("head", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

Thoughts?

**Comment by nekromant** [comment]
Hi! Sorry for the late reply, I haven't yet tried it running with 3.11. Perhaps a recent update of python or requests is needed. I'll give it a look along with other PR this weekend

**Comment by nekromant** [comment]
This should be working now, thanks to @gustou. If not, please reopen. The release should be up at pypi some time soon.
